# Site settings
title: "Learning Locker V1 Documentation"
email: "hello@ht2labs.com"
description: "Documentation for Learning Locker, the open source learning record store."
source: "./src"
destination: "./out"

# Build settings
markdown: kramdown
permalink: pretty

# YAML Frontmatter variables
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"

